export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function BreedPageLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return <main className="w-full">{children}</main>;
}
