import { Raleway } from "next/font/google";

import "./globals.css";
import { FaveList } from "@/components/faves/FaveList";

const font = Raleway({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={font.className}>
            <body>
                <main className="max-w-6xl m-auto flex flex-col items-center justify-center p-16">
                    {children}

                    <FaveList />
                </main>
            </body>
        </html>
    );
}
